# Site settings
name: Kezhen Yan/ Haoliang You
location: University of Pennsylvania
company: ESE 519
position: Electronic Piano
github: https://github.com/akiyamask
facebook: https://www.facebook.com/
phone: 132653351111
email: kezhen@seas.upenn.edu

baseurl: "/resume"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

